[project]
name = "masala"
version = "0.1.0"
description = "Implementation of ml, dl, math algorithms with tests. Additional notebooks for deeper understanding"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "numpy>=2.2.4",
]
